version: "3.8"

services:
  log_generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log_generator
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logs_viewer:
    build: .
    container_name: logs_viewer
    restart: always
    ports:
      - "3000:3000"
      - "9090:9090"
